org: okiro
service: image-upload

stages:
  default:
    params:
      tableName: "image-metadata-table-${sls:stage}"
      bucketName: "image-upload-bucket-${sls:stage}-okiro"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ImageMetaDataTable, Arn]
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource:
            - arn:aws:s3:::${param:bucketName}/*
        - Effect: Allow
          Action:
            - s3:ListBucket
          Resource:
            - arn:aws:s3:::${param:bucketName}

  environment:
    METADATA_TABLE: ${param:tableName}
    BUCKET_NAME: ${param:bucketName}

functions:
  uploadImage:
    handler: src/image-upload/handler.handler
    events:
      - httpApi: "*"
  processImage:
    handler: src/image-processor/handler.handler
    events:
      - s3:
          bucket: ${param:bucketName}
          event: s3:ObjectCreated:*
          rules:
            - prefix: images/
            - suffix: .png
          existing: true

resources:
  Resources:
    ImageMetaDataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: imageId
            AttributeType: S
        KeySchema:
          - AttributeName: imageId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:tableName}
    ImageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${param:bucketName}
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - "*"
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              AllowedHeaders:
                - "*"
              MaxAge: 3000